apiVersion: v1
kind: Pod
metadata:
  name: dotnetcore
  namespace: production
  labels:
    env: prod
    org: microsoft
spec:
  containers:
    - name: dotnetcore
      image: mcr.microsoft.com/dotnet/aspnet:6.0
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"